name: Tests
on: push

jobs:
  # <---------------- TEST BASIC CONFIG ------------------>
  basic:
    name: Basic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Basic Test
        uses: ./
        with:
         image: alpine:latest
         accept-extensions: pem
      - name: Upload Reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Basic Report
          path: dockle-report.json
  # <--------------- TEST ADVANCED CONFIG ---------------->
  advanced:
    name: Advanced
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Advanced Test
        uses: ./
        with:
          image: alpine:latest
          report-format: sarif
          report-name: dockle
          failure-threshold: fatal
          exit-code: 1
          dockle-version: 0.4.1
          accept-extensions: pem
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: dockle.sarif